#xlfile:  '/media/vmshare/caNano/Protocols-With-DOIs-8-15-25.xlsx'
#sheet: 'Sheet1'
xlfile: '/media/vmshare/caNano/GC Data Mapping_submission_templates_12032025.xlsx'
sheet: 
  - 'Protocol'
  - 'Publication'
  - 'Characterization '
  - 'Sample Node'
  - 'Composition'
  - 'File'
  - 'Study'
  - 'Investigator'
writedir: './pages/'
# The scope entry determines if all files are created or only new files.  Valid values are 'all' (Generate and entire new set of .md files),  'new' (only generate new DOI files), and 'index (only generate a new index.md file)'
scope: 'new'
sqlitefile: 'canano.db'